unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare

set -g @tokyo-night-tmux_show_battery_widget 1

set -g status-position top

# Image.nvim
set -gq allow-passthrough on
set -g visual-activity off

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
